<?php

namespace Drupal\content_sync;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\content_sync\DependencyResolver\ExportQueueResolver;
use Drupal\content_sync\DependencyResolver\ImportQueueResolver;
use Drupal\content_sync\Exporter\ContentExporterInterface;
use Drupal\content_sync\Importer\ContentImporterInterface;
use Symfony\Component\Serializer\Serializer;

/**
 * Content Sync Manager.
 */
class ContentSyncManager implements ContentSyncManagerInterface {

  const DELIMITER = '.';

  /**
   * Serializer implementation.
   *
   * @var \Symfony\Component\Serializer\Serializer
   */
  protected $serializer;

  /**
   * EntityTypeManager implementation.
   *
   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  protected $entityTypeManager;

  /**
   * ContentExporter  implementation.
   *
   * @var \Drupal\content_sync\Exporter\ContentExporterInterface
   */
  protected $contentExporter;

  /**
   * ContentImporter implementation.
   *
   * @var \Drupal\content_sync\Importer\ContentImporterInterface
   */
  protected $contentImporter;

  /**
   * ContentSyncManager constructor.
   */
  public function __construct(Serializer $serializer, EntityTypeManagerInterface $entity_type_manager, ContentExporterInterface $content_exporter, ContentImporterInterface $content_importer) {
    $this->serializer = $serializer;
    $this->entityTypeManager = $entity_type_manager;
    $this->contentExporter = $content_exporter;
    $this->contentImporter = $content_importer;
  }

  /**
   * The function returns the contentExporter property the current object.
   *
   * @return \Drupal\content_sync\Exporter\ContentExporterInterface
   *   the contentExporter property the current object
   */
  public function getContentExporter() {
    return $this->contentExporter;
  }

  /**
   * The function returns the content importer object.
   *
   * @return \Drupal\content_sync\Importer\ContentImporterInterface
   *   The `contentImporter` property is being returned.
   */
  public function getContentImporter() {
    return $this->contentImporter;
  }

  /**
   * The function generates an import queue by processing files in a directory.
   *
   * @param mixed $file_names
   *   Is an array containing the names of files to be processed for import.
   * @param string $directory
   *   Represents the base directory where the files are located.
   *
   * @return array
   *   containing entities that have  been decoded from YAML files
   */
  public function generateImportQueue($file_names, $directory) {
    $queue = [];
    foreach ($file_names as $file) {
      if ($file == 'site.uuid') {
        continue;
      }
      $ids = explode('.', $file);
      [$entity_type_id, $bundle] = $ids;
      $file_path = $directory . "/" . $entity_type_id . "/" . $bundle . "/" . $file . ".yml";
      if (!file_exists($file_path) || !$this->isValidFilename($file)) {
        continue;
      }
      $content = file_get_contents($file_path);
      $format = $this->contentImporter->getFormat();
      $decoded_entity = $this->serializer->decode($content, $format);
      $decoded_entities[$file] = $decoded_entity;
    }
    if (!empty($decoded_entities)) {
      $resolver = new ImportQueueResolver($decoded_entities);
      $queue = $resolver->resolve();
    }
    return $queue;
  }

  /**
   * Creates an export queue based on decoded entities and visited entities.
   *
   * @param array $decoded_entities
   *   Decoded entities typically refer data structures that have been parsed.
   * @param array $visited
   *   Seems to be an array keeps track entities that have already been visited.
   *
   * @return mixed
   *   Returns the export queue generated by resolving the decoded
   *   entities using an `ExportQueueResolver`.
   */
  public function generateExportQueue($decoded_entities, $visited) {
    $queue = [];
    if (!empty($decoded_entities)) {
      $resolver = new ExportQueueResolver($decoded_entities, $visited);
      $queue = $resolver->resolve();
    }
    return $queue;
  }

  /**
   * The function returns the serializer property of the current object.
   *
   * @return \Symfony\Component\Serializer\Serializer
   *   The `serializer` property is being returned.
   */
  public function getSerializer() {
    return $this->serializer;
  }

  /**
   * The function returns the entityTypeManager property of the current object.
   *
   * @return \Drupal\Core\Entity\EntityTypeManagerInterface
   *   Property is being returned.
   */
  public function getEntityTypeManager() {
    return $this->entityTypeManager;
  }

  /**
   * Checks if a filename contains exactly three parts.
   *
   * @param string $filename
   *   Filename as a parameter and checks if it can be split.
   *
   * @return bool
   *   value indicating whether the filename contains exactly 3 parts
   */
  protected function isValidFilename($filename) {
    $parts = explode(static::DELIMITER, $filename);
    return count($parts) === 3;
  }

}
